services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=personal_finances
      - POSTGRES_USER=yubor
      - POSTGRES_PASSWORD=123yubor
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=yubor98@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123yubor
    ports:
       - 5050:80